import{i as d,S as m}from"./assets/vendor-5ObWk2rO.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&t(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function t(e){if(e.ep)return;e.ep=!0;const n=r(e);fetch(e.href,n)}})();const f="50461526-1c4ae7086be4914a89297c276";async function g(o){const s=`https://pixabay.com/api/?key=${f}&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true`,r=await fetch(s);if(!r.ok)throw new Error("API isteği başarısız");return await r.json()}const y=document.querySelector(".search-input"),h=document.querySelector(".search-button"),p=document.querySelector("#results-container"),u=document.getElementById("loader");h.addEventListener("click",async()=>{const o=y.value.trim();if(o){u.style.display="block";try{const s=await g(o);if(await new Promise(t=>setTimeout(t,1500)),p.innerHTML="",s.hits.length===0){d.warning({title:"Uyarı",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}s.hits.forEach(t=>{const e=document.createElement("a");e.href=t.largeImageURL,e.className="image-card";const n=`
        <strong>Tags:</strong> ${t.tags}<br>
        👍 ${t.likes} &nbsp;&nbsp;
        👁️ ${t.views} &nbsp;&nbsp;
        💬 ${t.comments} &nbsp;&nbsp;
        ⬇️ ${t.downloads}
      `;e.setAttribute("data-title",n),e.setAttribute("data-lightbox","gallery");const a=document.createElement("img");a.src=t.webformatURL,a.alt=t.tags;const i=document.createElement("div");i.className="image-info";const c=document.createElement("p");c.className="tags",c.textContent=`Tags: ${t.tags}`;const l=document.createElement("div");l.className="stats",l.innerHTML=`
        <span>👍 ${t.likes}</span>
        <span>👁️ ${t.views}</span>
        <span>💬 ${t.comments}</span>
        <span>⬇️ ${t.downloads}</span>
      `,i.appendChild(c),i.appendChild(l),e.appendChild(a),e.appendChild(i),p.appendChild(e)}),new m(".results-container a",{captionsData:"data-title",captionDelay:250,captionPosition:"bottom"}).refresh()}catch{d.error({title:"Hata",message:"Bir sorun oluştu. Lütfen daha sonra tekrar deneyin.",position:"topRight"})}finally{u.style.display="none"}}});
//# sourceMappingURL=index.js.map
